name: Deployment
on:
  push:
  workflow_dispatch:

jobs:
  get_stacks:
    name: Get Stacks
    environment: INT
    runs-on: [Linux]
    outputs:
      files: ${{ steps.files.outputs.files }}
      dirs-asc: ${{ steps.files.outputs.dirs }}
      dirs-dsc: ${{ steps.files.outputs.dirs-desc}}
    steps:
      - uses: actions/checkout@v3
      - name: Test - Helper
        id: files
        uses: otc-code/gh-actions/helper@main
        with:
          path: '${{ github.workspace }}/stacks'

  stack_test_deploy:
    name: Stack Deploy
    runs-on: [Linux]
    needs: get_stacks
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        stacks: ${{ fromjson(needs.get_stacks.outputs.dirs-asc) }}
    steps:
      - name: ${{ matrix.stacks }}
        run: |
          echo "Stackset: ${{ matrix.stacks }}"

  stack_test_destroy:
    name: Stack Destroy
    runs-on: [Linux]
    needs: get_stacks
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        stacks: ${{ fromjson(needs.get_stacks.outputs.dirs-dsc) }}
    steps:
      - name: ${{ matrix.stacks }}
        run: |
          echo "Stackset: ${{ matrix.stacks }}"
