on:
  push:

jobs:
  test:
    name: Test Matrix order
    runs-on: [otc-static]
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        stacks:
          - 0_BASE
          - 1_NET
          - 2_INF_DB
          - 3_INF_S3
          - 4_SYS_VM
          - 5_APP_ECS

    steps:
      - name: Ouput
        id: get_project
        run: |
          echo "Stackset: ${{ matrix.stacks }}"
