on:
  push:

jobs:
  jobs:

  get_stacks:
    name: Get Stacks
    environment: INT
    runs-on: [Linux]
    outputs:
      files: ${{ steps.files.outputs.files }}
      dirs: ${{ steps.files.outputs.dirs }}
    steps:
      - uses: actions/checkout@v3
      - name: Test - Helper
        id: files
        uses: otc-code/gh-actions/helper@main
        with:
          path: '${{ github.workspace }}/stacks'

  stack_test:
    name: Test Stacks order
    runs-on: [otc-static]
    needs: get_stacks
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        stacks: ${{ fromjson(needs.get_stacks.outputs.dirs) }}
    steps:
      - name: ${{ matrix.stacks }}
        run: |
          echo "Stackset: ${{ matrix.stacks }}"
